<?php
if(in_array($_SERVER['REMOTE_ADDR'],array('113.23.55.195'))){
    var_dump("trans");

}else {
    /**
     * Copyright © Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */

// @codingStandardsIgnoreFile

    /**  @var $block \Magento\Checkout\Block\Cart\Grid */
    ?>
    <?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
    <?= $block->getChildHtml('form_before') ?>
    <form action="<?= /* @escapeNotVerified */
    $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                     data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
            <?php endif ?>
            <table id="shopping-cart-table"
                   class="cart items data table"
                   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
                <caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */
                    __('Shopping Cart Items') ?></caption>

                <?php if (true) : ?>
                    <thead>
                    <tr>
                        <th class="col item" scope="col"><span><?= /* @escapeNotVerified */
                                __('Item') ?></span></th>
                    </tr>
                    </thead>

                    <?php foreach ($block->getWarehouseItems() as $_item): ?>
                        <?= $block->getItemHtml($_item) ?>
                    <?php endforeach ?>
                <?php else: ?>
                    <thead>
                    <tr>
                        <th class="col item" scope="col"><span><?= /* @escapeNotVerified */
                                __('Item') ?></span></th>
                        <th class="col price" scope="col"><span><?= /* @escapeNotVerified */
                                __('Price') ?></span></th>
                        <th class="col qty" scope="col"><span><?= /* @escapeNotVerified */
                                __('Qty') ?></span></th>
                        <th class="col subtotal" scope="col"><span><?= /* @escapeNotVerified */
                                __('Subtotal') ?></span></th>
                    </tr>
                    </thead>

                    <?php foreach ($block->getItems() as $_item): ?>
                        <?= $block->getItemHtml($_item) ?>
                    <?php endforeach ?>
                <?php endif; ?>
            </table>
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                     data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
            <?php endif ?>
        </div>
        <div class="cart main actions">
            <?php if ($block->getContinueShoppingUrl()): ?>
                <a class="action continue"
                   href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
                   title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                    <span><?= /* @escapeNotVerified */
                        __('Continue Shopping') ?></span>
                </a>
            <?php endif; ?>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= /* @escapeNotVerified */
                    __('Clear Shopping Cart') ?></span>
            </button>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-item-update=""
                    value="update_qty"
                    title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                    class="action update">
                <span><?= /* @escapeNotVerified */
                    __('Update Shopping Cart') ?></span>
            </button>
            <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
        </div>
    </form>
    <?= $block->getChildHtml('checkout.cart.order.actions') ?>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>

    <script>
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function () {
                $('form.form-cart input').on("keypress", function (e) {
                    if (e.which == 13) {
                        e.preventDefault();
                        $(this).trigger("blur");
                        return false;
                    }
                });

                $(document).on('focus', ".cart-wh-size-qty .qty", function () {

                    var maxqty = $(this).data('max');
                    var currval = $(this).val();
                    if (currval > maxqty) {
                        $(this).val(maxqty);
                    }

                    if ($(this).val() == 0) {
                        $(this).val('');
                    }
                });
                $(document).on('blur', ".cart-wh-size-qty .qty", function () {
                    var maxqty = $(this).data('max');
                    var currval = $(this).val();
                    if (currval > maxqty) {
                        $(this).val(maxqty);
                    }

                    if ($(this).val() === '' || maxqty == 0) {
                        $(this).val(0);
                    }
                });
            });
        });
    </script>
    <?php
}
?>
